name: Check Rust

on:
  workflow_call:
    inputs:
      rust-version:
        description: "Rust version to use"
        required: true
        type: string

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: clippy

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build all targets
        run: cargo build --all-targets --all-features

      - name: Run all tests
        run: cargo test --all-targets --all-features